workflows:
  android-release:
    name: بناء تطبيق ديون البقالة
    max_build_duration: 30
    instance_type: linux_x2
    environment:
      flutter: stable
    scripts:
      - name: تحميل المكتبات
        script: flutter pub get
      - name: إنشاء ملفات Android
        script: |
          flutter create --platforms=android --org com.bakala .
      - name: بناء APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
